---
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
site:
  title: Rego policies related to HACBS Enterprise Contract
  url: https://hacbs-contract.github.io/ec-policies/
  start_page: ec-policies::index.adoc
  robots: allow
content:
  sources:
    - url: .
      start_path: ./antora/docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora/supplemental-ui
output:
  dir: ./public
antora:
  extensions:
  - require: ./antora/ec-policies-antora-extension/index.js
